### ISSUE TITLE
Support Packstation in Response

### ISSUE THREAD

**Issue by sprankhub** [netresearch/deutschepost-sdk-addressfactory#1]
In `\PostDirekt\Sdk\AddressfactoryDirect\Model\Mapper\RecordResponseMapper::map`, the class for packing stations `\PostDirekt\Sdk\AddressfactoryDirect\Model\Common\PackstationType` is not mapped to anything, which means that packing station data will be lost. So if I check a packing station address via this SDK and read the response, I get an empty address and no packing station address at all.

Doesn't this mean that https://github.com/netresearch/deutschepost-module-addressfactory-m2 currently also does not support packing stations?

**Comment by powli** [comment]
Hey @sprankhub,

yes indeed, that is not handled properly. Reason is that the main use case for the mentioned Magento module was the calculation of a deliverability score (which would be deliverable for packing stations always) therefore it was decided to not support them at all.
Feel free to create a PR if you need this feature for your use case.

**Comment by sprankhub** [comment]
Thanks for your feedback @powli!

There is a high chance of a PR, because I think I definitely need this.

Just because an address is a packing station does not mean that it is deliverable per se. If it is entered via the official location finder, maybe it is. But in many cases, it is entered manually. As in: We cannot force our client nor their customers to actually use the location finder functionality. And if the packing station is entered manually, many things can be wrong: The post number could be wrong (e.g. one wrong digit), the packing station number could be wrong, the postal code could be wrong etc. Hence, I think this should also be handled in the module. However, I will add an issue in the respective repository for this.

**Comment by sprankhub** [comment]
See https://github.com/netresearch/deutschepost-sdk-addressfactory/pull/2

**Comment by powli** [comment]
PR is merged, thanks again for your contribution.
